require:
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable

Naming/MethodName:
  IgnoredPatterns:
    - Struct

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
